/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "CreateLinkHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Links": {
      "linksTable": {
        "arn": string
        "endpoint": string
        "name": string
      }
      "type": "sst.sst.Linkable"
    }
    "LinksApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "LinksTable": {
      "arn": string
      "endpoint": string
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ListLinksHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
